#index:
#    path: /
#    controller: App\Controller\DefaultController::index
accueil:
    path: /accueil
    controller: App\Controller\EtudiantController::index
    
etudiantAjouter:
    path: /etudiant/ajouter
    controller: App\Controller\EtudiantController::ajouterEtudiant
    
etudiantConsulter:
    path: /etudiant/consulter/{id}
    controller: App\Controller\EtudiantController::consulterEtudiant
    
etudiantLister:
    path: /etudiant/lister
    controller: App\Controller\EtudiantController::listerEtudiant